/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DetailsComponent: typeof import('./src/components/DetailsComponent.vue')['default']
    DocumentListComponent: typeof import('./src/components/documentListComponent.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    KaspiCard: typeof import('./src/components/kaspiCard.vue')['default']
    MiniNavbarComponent: typeof import('./src/components/MiniNavbarComponent.vue')['default']
    'MiniNavbarComponent.vue': typeof import('./src/components/MiniNavbarComponent.vue')['default']
    NavbarComponent: typeof import('./src/components/NavbarComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
    TabsComponent: typeof import('./src/components/TabsComponent.vue')['default']
    TabWrapper: typeof import('./src/components/TabWrapper.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
  }
}
