/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonSettingComponent: typeof import('./src/components/ButtonSettingComponent.vue')['default']
    DetailsComponent: typeof import('./src/components/DetailsComponent.vue')['default']
    DocumentListComponent: typeof import('./src/components/documentListComponent.vue')['default']
    DocumentStock: typeof import('./src/components/DocumentComponents/DocumentStock.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    KaspiCard: typeof import('./src/components/kaspiCard.vue')['default']
    ModalComponent: typeof import('./src/components/ModalComponent.vue')['default']
    NavbarComponent: typeof import('./src/components/Navbar/NavbarComponent.vue')['default']
    RedactComponent: typeof import('./src/components/DocumentComponents/RedactComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabsComponent: typeof import('./src/components/Navbar/TabsComponent.vue')['default']
    ToastComponent: typeof import('./src/components/ToastComponent.vue')['default']
  }
}
