/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/document/driverlc': RouteRecordInfo<'/document/driverlc', '/document/driverlc', Record<never, never>, Record<never, never>>,
    '/document/id': RouteRecordInfo<'/document/id', '/document/id', Record<never, never>, Record<never, never>>,
    '/document/passport': RouteRecordInfo<'/document/passport', '/document/passport', Record<never, never>, Record<never, never>>,
    '/document/studentid': RouteRecordInfo<'/document/studentid', '/document/studentid', Record<never, never>, Record<never, never>>,
  }
}
